#!/bin/bash

## Extract all namespaces from the base jsonnet
TEMPORARY_TEMPLATE_NAME=_temp.jsonnet
echo "local nsbase = import \"mesh-namespaces.jsonnet\"; std.join(' ', nsbase.allNs)" > $TEMPORARY_TEMPLATE_NAME
all_namespaces=$(./../../jsonnet/jsonnet ${TEMPORARY_TEMPLATE_NAME} | sed -e "s|\"||g")
echo "all_namespaces=${all_namespaces=}"
rm $TEMPORARY_TEMPLATE_NAME


## Generate namespace files
rm ./templates/mesh-svcs-ns-*.jsonnet
for namespaceName in $all_namespaces; do
    out_file_name="./templates/mesh-svcs-ns-${namespaceName}.jsonnet"

    echo -e "## Autogenerated file.\n\n" > $out_file_name
    echo -e "local nsbase = import \"namespaces/mesh-namespaces.jsonnet\";" >> $out_file_name
    echo -e "local configs = import \"config.jsonnet\";" >> $out_file_name
    echo -e "if (nsbase.shouldDeployToKingdom(\"${namespaceName}\", configs.kingdom)) then" >> $out_file_name
    echo -e "        nsbase.newMeshNamespace(\"${namespaceName}\")" >> $out_file_name
    echo -e "else \"SKIP\"" >> $out_file_name
done