#Generated by manifestctl/generate-pool-list/module-main.go DO NOT EDIT BY HAND!
{
  "generatedPools": [
    {
      "namespaces": [
        "csc-sam"
      ],
      "access": [
        "team/CSC_Sam"
      ],
      "controlEstate": "cdu-sam",
      "estate": "cdu-sam",
      "kingdom": "cdu",
      "superPod": "None"
    },
    {
      "namespaces": [
        "gater"
      ],
      "access": [
        "team/Gater"
      ],
      "controlEstate": "cdu-sam",
      "estate": "cdu-sam_gater",
      "kingdom": "cdu",
      "superPod": "None"
    },
    {
      "namespaces": [
        "csc-sam"
      ],
      "access": [
        "team/CSC_Sam"
      ],
      "controlEstate": "chx-sam",
      "estate": "chx-sam",
      "kingdom": "chx",
      "superPod": "None"
    },
    {
      "namespaces": [
        "gater"
      ],
      "access": [
        "team/Gater"
      ],
      "controlEstate": "chx-sam",
      "estate": "chx-sam_gater",
      "kingdom": "chx",
      "superPod": "None"
    },
    {
      "namespaces": [
        "csc-sam"
      ],
      "access": [
        "team/CSC_Sam"
      ],
      "controlEstate": "dfw-sam",
      "estate": "dfw-sam",
      "kingdom": "dfw",
      "superPod": "None"
    },
    {
      "namespaces": [
        "legostore",
        "storage-foundation"
      ],
      "access": [
        "team/LegoStore",
        "team/Storage_Foundation"
      ],
      "controlEstate": "dfw-sam",
      "estate": "dfw-sam_ceph",
      "kingdom": "dfw",
      "superPod": "None"
    },
    {
      "namespaces": [
        "chatbot"
      ],
      "access": [
        "team/chatbot"
      ],
      "controlEstate": "dfw-sam",
      "estate": "dfw-sam_chatbot_kingdom",
      "kingdom": "dfw",
      "superPod": "None"
    },
    {
      "namespaces": [
        "cloudatlas"
      ],
      "access": [
        "team/CloudAtlas"
      ],
      "controlEstate": "dfw-sam",
      "estate": "dfw-sam_cloudatlas",
      "kingdom": "dfw",
      "superPod": "None"
    },
    {
      "namespaces": [
        "cloudatlas"
      ],
      "access": [
        "team/CloudAtlas"
      ],
      "controlEstate": "dfw-sam",
      "estate": "dfw-sam_cloudatlas_dir",
      "kingdom": "dfw",
      "superPod": "None"
    },
    {
      "namespaces": [
        "gater",
        "ccait"
      ],
      "access": [
        "team/Gater",
        "team/CCAIT"
      ],
      "controlEstate": "dfw-sam",
      "estate": "dfw-sam_gater",
      "kingdom": "dfw",
      "superPod": "None"
    },
    {
      "namespaces": [
        "communities"
      ],
      "access": [
        "team/communities"
      ],
      "controlEstate": "dfw-sam",
      "estate": "dfw-sam_moderation_einstein",
      "kingdom": "dfw",
      "superPod": "None"
    },
    {
      "namespaces": [
        "csc-health"
      ],
      "access": [
        "team/CSC_Health"
      ],
      "controlEstate": "dfw-sam",
      "estate": "dfw-sam_report_collector",
      "kingdom": "dfw",
      "superPod": "None"
    },
    {
      "namespaces": [
        "sf-store",
        "storage-foundation"
      ],
      "access": [
        "team/SF_Store",
        "team/Storage_Foundation"
      ],
      "controlEstate": "dfw-sam",
      "estate": "dfw-sam_sfstore",
      "kingdom": "dfw",
      "superPod": "None"
    },
    {
      "namespaces": [
        "casp"
      ],
      "access": [
        "team/CASP"
      ],
      "controlEstate": "dfw-sam",
      "estate": "dfw-sam_warden",
      "kingdom": "dfw",
      "superPod": "None"
    },
    {
      "namespaces": [
        "cache-as-a-service-sp1"
      ],
      "access": [
        "team/Cache_As_A_service"
      ],
      "controlEstate": "dfw-sam",
      "estate": "dfw-sp1-sam_caas",
      "kingdom": "dfw",
      "superPod": "sp1"
    },
    {
      "namespaces": [
        "cache-as-a-service-sp2"
      ],
      "access": [
        "team/Cache_As_A_service"
      ],
      "controlEstate": "dfw-sam",
      "estate": "dfw-sp2-sam_caas",
      "kingdom": "dfw",
      "superPod": "sp2"
    },
    {
      "namespaces": [
        "cache-as-a-service-sp3"
      ],
      "access": [
        "team/Cache_As_A_service"
      ],
      "controlEstate": "dfw-sam",
      "estate": "dfw-sp3-sam_caas",
      "kingdom": "dfw",
      "superPod": "sp3"
    },
    {
      "namespaces": [
        "cache-as-a-service-sp4"
      ],
      "access": [
        "team/Cache_As_A_service"
      ],
      "controlEstate": "dfw-sam",
      "estate": "dfw-sp4-sam_caas",
      "kingdom": "dfw",
      "superPod": "sp4"
    },
    {
      "namespaces": [
        "csc-sam"
      ],
      "access": [
        "team/CSC_Sam"
      ],
      "controlEstate": "frf-sam",
      "estate": "frf-sam",
      "kingdom": "frf",
      "superPod": "None"
    },
    {
      "namespaces": [
        "legostore",
        "storage-foundation"
      ],
      "access": [
        "team/LegoStore",
        "team/Storage_Foundation"
      ],
      "controlEstate": "frf-sam",
      "estate": "frf-sam_ceph",
      "kingdom": "frf",
      "superPod": "None"
    },
    {
      "namespaces": [
        "chatbot"
      ],
      "access": [
        "team/chatbot"
      ],
      "controlEstate": "frf-sam",
      "estate": "frf-sam_chatbot_kingdom",
      "kingdom": "frf",
      "superPod": "None"
    },
    {
      "namespaces": [
        "cloudatlas"
      ],
      "access": [
        "team/CloudAtlas"
      ],
      "controlEstate": "frf-sam",
      "estate": "frf-sam_cloudatlas",
      "kingdom": "frf",
      "superPod": "None"
    },
    {
      "namespaces": [
        "cloudatlas"
      ],
      "access": [
        "team/CloudAtlas"
      ],
      "controlEstate": "frf-sam",
      "estate": "frf-sam_cloudatlas_dir",
      "kingdom": "frf",
      "superPod": "None"
    },
    {
      "namespaces": [
        "gater"
      ],
      "access": [
        "team/Gater"
      ],
      "controlEstate": "frf-sam",
      "estate": "frf-sam_gater",
      "kingdom": "frf",
      "superPod": "None"
    },
    {
      "namespaces": [
        "communities"
      ],
      "access": [
        "team/communities"
      ],
      "controlEstate": "frf-sam",
      "estate": "frf-sam_moderation_einstein",
      "kingdom": "frf",
      "superPod": "None"
    },
    {
      "namespaces": [
        "csc-health"
      ],
      "access": [
        "team/CSC_Health"
      ],
      "controlEstate": "frf-sam",
      "estate": "frf-sam_report_collector",
      "kingdom": "frf",
      "superPod": "None"
    },
    {
      "namespaces": [
        "sf-store",
        "storage-foundation"
      ],
      "access": [
        "team/SF_Store",
        "team/Storage_Foundation"
      ],
      "controlEstate": "frf-sam",
      "estate": "frf-sam_sfstore",
      "kingdom": "frf",
      "superPod": "None"
    },
    {
      "namespaces": [
        "casp"
      ],
      "access": [
        "team/CASP"
      ],
      "controlEstate": "frf-sam",
      "estate": "frf-sam_warden",
      "kingdom": "frf",
      "superPod": "None"
    },
    {
      "namespaces": [
        "cache-as-a-service-sp1"
      ],
      "access": [
        "team/Cache_As_A_service"
      ],
      "controlEstate": "frf-sam",
      "estate": "frf-sp1-sam_caas",
      "kingdom": "frf",
      "superPod": "sp1"
    },
    {
      "namespaces": [
        "csc-sam"
      ],
      "access": [
        "team/CSC_Sam"
      ],
      "controlEstate": "hnd-sam",
      "estate": "hnd-sam",
      "kingdom": "hnd",
      "superPod": "None"
    },
    {
      "namespaces": [
        "legostore",
        "storage-foundation"
      ],
      "access": [
        "team/LegoStore",
        "team/Storage_Foundation"
      ],
      "controlEstate": "hnd-sam",
      "estate": "hnd-sam_ceph",
      "kingdom": "hnd",
      "superPod": "None"
    },
    {
      "namespaces": [
        "chatbot"
      ],
      "access": [
        "team/chatbot"
      ],
      "controlEstate": "hnd-sam",
      "estate": "hnd-sam_chatbot_kingdom",
      "kingdom": "hnd",
      "superPod": "None"
    },
    {
      "namespaces": [
        "cloudatlas"
      ],
      "access": [
        "team/CloudAtlas"
      ],
      "controlEstate": "hnd-sam",
      "estate": "hnd-sam_cloudatlas",
      "kingdom": "hnd",
      "superPod": "None"
    },
    {
      "namespaces": [
        "cloudatlas"
      ],
      "access": [
        "team/CloudAtlas"
      ],
      "controlEstate": "hnd-sam",
      "estate": "hnd-sam_cloudatlas_dir",
      "kingdom": "hnd",
      "superPod": "None"
    },
    {
      "namespaces": [
        "gater"
      ],
      "access": [
        "team/Gater"
      ],
      "controlEstate": "hnd-sam",
      "estate": "hnd-sam_gater",
      "kingdom": "hnd",
      "superPod": "None"
    },
    {
      "namespaces": [
        "communities"
      ],
      "access": [
        "team/communities"
      ],
      "controlEstate": "hnd-sam",
      "estate": "hnd-sam_moderation_einstein",
      "kingdom": "hnd",
      "superPod": "None"
    },
    {
      "namespaces": [
        "csc-health"
      ],
      "access": [
        "team/CSC_Health"
      ],
      "controlEstate": "hnd-sam",
      "estate": "hnd-sam_report_collector",
      "kingdom": "hnd",
      "superPod": "None"
    },
    {
      "namespaces": [
        "sf-store",
        "storage-foundation"
      ],
      "access": [
        "team/SF_Store",
        "team/Storage_Foundation"
      ],
      "controlEstate": "hnd-sam",
      "estate": "hnd-sam_sfstore",
      "kingdom": "hnd",
      "superPod": "None"
    },
    {
      "namespaces": [
        "casp"
      ],
      "access": [
        "team/CASP"
      ],
      "controlEstate": "hnd-sam",
      "estate": "hnd-sam_warden",
      "kingdom": "hnd",
      "superPod": "None"
    },
    {
      "namespaces": [
        "cache-as-a-service-sp1"
      ],
      "access": [
        "team/Cache_As_A_service"
      ],
      "controlEstate": "hnd-sam",
      "estate": "hnd-sp1-sam_caas",
      "kingdom": "hnd",
      "superPod": "sp1"
    },
    {
      "namespaces": [
        "csc-sam"
      ],
      "access": [
        "team/CSC_Sam"
      ],
      "controlEstate": "iad-sam",
      "estate": "iad-sam",
      "kingdom": "iad",
      "superPod": "None"
    },
    {
      "namespaces": [
        "legostore",
        "storage-foundation"
      ],
      "access": [
        "team/LegoStore",
        "team/Storage_Foundation"
      ],
      "controlEstate": "iad-sam",
      "estate": "iad-sam_ceph",
      "kingdom": "iad",
      "superPod": "None"
    },
    {
      "namespaces": [
        "chatbot"
      ],
      "access": [
        "team/chatbot"
      ],
      "controlEstate": "iad-sam",
      "estate": "iad-sam_chatbot_kingdom",
      "kingdom": "iad",
      "superPod": "None"
    },
    {
      "namespaces": [
        "cloudatlas"
      ],
      "access": [
        "team/CloudAtlas"
      ],
      "controlEstate": "iad-sam",
      "estate": "iad-sam_cloudatlas",
      "kingdom": "iad",
      "superPod": "None"
    },
    {
      "namespaces": [
        "cloudatlas"
      ],
      "access": [
        "team/CloudAtlas"
      ],
      "controlEstate": "iad-sam",
      "estate": "iad-sam_cloudatlas_dir",
      "kingdom": "iad",
      "superPod": "None"
    },
    {
      "namespaces": [
        "gater"
      ],
      "access": [
        "team/Gater"
      ],
      "controlEstate": "iad-sam",
      "estate": "iad-sam_gater",
      "kingdom": "iad",
      "superPod": "None"
    },
    {
      "namespaces": [
        "communities"
      ],
      "access": [
        "team/communities"
      ],
      "controlEstate": "iad-sam",
      "estate": "iad-sam_moderation_einstein",
      "kingdom": "iad",
      "superPod": "None"
    },
    {
      "namespaces": [
        "csc-health"
      ],
      "access": [
        "team/CSC_Health"
      ],
      "controlEstate": "iad-sam",
      "estate": "iad-sam_report_collector",
      "kingdom": "iad",
      "superPod": "None"
    },
    {
      "namespaces": [
        "sf-store",
        "storage-foundation"
      ],
      "access": [
        "team/SF_Store",
        "team/Storage_Foundation"
      ],
      "controlEstate": "iad-sam",
      "estate": "iad-sam_sfstore",
      "kingdom": "iad",
      "superPod": "None"
    },
    {
      "namespaces": [
        "casp"
      ],
      "access": [
        "team/CASP"
      ],
      "controlEstate": "iad-sam",
      "estate": "iad-sam_warden",
      "kingdom": "iad",
      "superPod": "None"
    },
    {
      "namespaces": [
        "cache-as-a-service-sp1"
      ],
      "access": [
        "team/Cache_As_A_service"
      ],
      "controlEstate": "iad-sam",
      "estate": "iad-sp1-sam_caas",
      "kingdom": "iad",
      "superPod": "sp1"
    },
    {
      "namespaces": [
        "cache-as-a-service-sp2"
      ],
      "access": [
        "team/Cache_As_A_service"
      ],
      "controlEstate": "iad-sam",
      "estate": "iad-sp2-sam_caas",
      "kingdom": "iad",
      "superPod": "sp2"
    },
    {
      "namespaces": [
        "csc-sam"
      ],
      "access": [
        "team/CSC_Sam"
      ],
      "controlEstate": "ord-sam",
      "estate": "ord-sam",
      "kingdom": "ord",
      "superPod": "None"
    },
    {
      "namespaces": [
        "legostore",
        "storage-foundation"
      ],
      "access": [
        "team/LegoStore",
        "team/Storage_Foundation"
      ],
      "controlEstate": "ord-sam",
      "estate": "ord-sam_ceph",
      "kingdom": "ord",
      "superPod": "None"
    },
    {
      "namespaces": [
        "chatbot"
      ],
      "access": [
        "team/chatbot"
      ],
      "controlEstate": "ord-sam",
      "estate": "ord-sam_chatbot_kingdom",
      "kingdom": "ord",
      "superPod": "None"
    },
    {
      "namespaces": [
        "cloudatlas"
      ],
      "access": [
        "team/CloudAtlas"
      ],
      "controlEstate": "ord-sam",
      "estate": "ord-sam_cloudatlas",
      "kingdom": "ord",
      "superPod": "None"
    },
    {
      "namespaces": [
        "cloudatlas"
      ],
      "access": [
        "team/CloudAtlas"
      ],
      "controlEstate": "ord-sam",
      "estate": "ord-sam_cloudatlas_dir",
      "kingdom": "ord",
      "superPod": "None"
    },
    {
      "namespaces": [
        "gater"
      ],
      "access": [
        "team/Gater"
      ],
      "controlEstate": "ord-sam",
      "estate": "ord-sam_gater",
      "kingdom": "ord",
      "superPod": "None"
    },
    {
      "namespaces": [
        "communities"
      ],
      "access": [
        "team/communities"
      ],
      "controlEstate": "ord-sam",
      "estate": "ord-sam_moderation_einstein",
      "kingdom": "ord",
      "superPod": "None"
    },
    {
      "namespaces": [
        "csc-health"
      ],
      "access": [
        "team/CSC_Health"
      ],
      "controlEstate": "ord-sam",
      "estate": "ord-sam_report_collector",
      "kingdom": "ord",
      "superPod": "None"
    },
    {
      "namespaces": [
        "sf-store",
        "storage-foundation"
      ],
      "access": [
        "team/SF_Store",
        "team/Storage_Foundation"
      ],
      "controlEstate": "ord-sam",
      "estate": "ord-sam_sfstore",
      "kingdom": "ord",
      "superPod": "None"
    },
    {
      "namespaces": [
        "casp"
      ],
      "access": [
        "team/CASP"
      ],
      "controlEstate": "ord-sam",
      "estate": "ord-sam_warden",
      "kingdom": "ord",
      "superPod": "None"
    },
    {
      "namespaces": [
        "cache-as-a-service-sp1"
      ],
      "access": [
        "team/Cache_As_A_service"
      ],
      "controlEstate": "ord-sam",
      "estate": "ord-sp1-sam_caas",
      "kingdom": "ord",
      "superPod": "sp1"
    },
    {
      "namespaces": [
        "cache-as-a-service-sp2"
      ],
      "access": [
        "team/Cache_As_A_service"
      ],
      "controlEstate": "ord-sam",
      "estate": "ord-sp2-sam_caas",
      "kingdom": "ord",
      "superPod": "sp2"
    },
    {
      "namespaces": [
        "csc-sam"
      ],
      "access": [
        "team/CSC_Sam"
      ],
      "controlEstate": "par-sam",
      "estate": "par-sam",
      "kingdom": "par",
      "superPod": "None"
    },
    {
      "namespaces": [
        "legostore",
        "storage-foundation"
      ],
      "access": [
        "team/LegoStore",
        "team/Storage_Foundation"
      ],
      "controlEstate": "par-sam",
      "estate": "par-sam_ceph",
      "kingdom": "par",
      "superPod": "None"
    },
    {
      "namespaces": [
        "chatbot"
      ],
      "access": [
        "team/chatbot"
      ],
      "controlEstate": "par-sam",
      "estate": "par-sam_chatbot_kingdom",
      "kingdom": "par",
      "superPod": "None"
    },
    {
      "namespaces": [
        "cloudatlas"
      ],
      "access": [
        "team/CloudAtlas"
      ],
      "controlEstate": "par-sam",
      "estate": "par-sam_cloudatlas",
      "kingdom": "par",
      "superPod": "None"
    },
    {
      "namespaces": [
        "cloudatlas"
      ],
      "access": [
        "team/CloudAtlas"
      ],
      "controlEstate": "par-sam",
      "estate": "par-sam_cloudatlas_dir",
      "kingdom": "par",
      "superPod": "None"
    },
    {
      "namespaces": [
        "gater",
        "ccait"
      ],
      "access": [
        "team/Gater",
        "team/CCAIT"
      ],
      "controlEstate": "par-sam",
      "estate": "par-sam_gater",
      "kingdom": "par",
      "superPod": "None"
    },
    {
      "namespaces": [
        "communities"
      ],
      "access": [
        "team/communities"
      ],
      "controlEstate": "par-sam",
      "estate": "par-sam_moderation_einstein",
      "kingdom": "par",
      "superPod": "None"
    },
    {
      "namespaces": [
        "csc-health"
      ],
      "access": [
        "team/CSC_Health"
      ],
      "controlEstate": "par-sam",
      "estate": "par-sam_report_collector",
      "kingdom": "par",
      "superPod": "None"
    },
    {
      "namespaces": [
        "sf-store",
        "storage-foundation"
      ],
      "access": [
        "team/SF_Store",
        "team/Storage_Foundation"
      ],
      "controlEstate": "par-sam",
      "estate": "par-sam_sfstore",
      "kingdom": "par",
      "superPod": "None"
    },
    {
      "namespaces": [
        "casp"
      ],
      "access": [
        "team/CASP"
      ],
      "controlEstate": "par-sam",
      "estate": "par-sam_warden",
      "kingdom": "par",
      "superPod": "None"
    },
    {
      "namespaces": [
        "cache-as-a-service-sp1"
      ],
      "access": [
        "team/Cache_As_A_service"
      ],
      "controlEstate": "par-sam",
      "estate": "par-sp1-sam_caas",
      "kingdom": "par",
      "superPod": "sp1"
    },
    {
      "namespaces": [
        "csc-sam"
      ],
      "access": [
        "team/CSC_Sam"
      ],
      "controlEstate": "phx-sam",
      "estate": "phx-sam",
      "kingdom": "phx",
      "superPod": "None"
    },
    {
      "namespaces": [
        "legostore",
        "storage-foundation"
      ],
      "access": [
        "team/LegoStore",
        "team/Storage_Foundation"
      ],
      "controlEstate": "phx-sam",
      "estate": "phx-sam_ceph",
      "kingdom": "phx",
      "superPod": "None"
    },
    {
      "namespaces": [
        "chatbot"
      ],
      "access": [
        "team/chatbot"
      ],
      "controlEstate": "phx-sam",
      "estate": "phx-sam_chatbot_kingdom",
      "kingdom": "phx",
      "superPod": "None"
    },
    {
      "namespaces": [
        "cloudatlas"
      ],
      "access": [
        "team/CloudAtlas"
      ],
      "controlEstate": "phx-sam",
      "estate": "phx-sam_cloudatlas",
      "kingdom": "phx",
      "superPod": "None"
    },
    {
      "namespaces": [
        "cloudatlas"
      ],
      "access": [
        "team/CloudAtlas"
      ],
      "controlEstate": "phx-sam",
      "estate": "phx-sam_cloudatlas_dir",
      "kingdom": "phx",
      "superPod": "None"
    },
    {
      "namespaces": [
        "gater",
        "ccait"
      ],
      "access": [
        "team/Gater",
        "team/CCAIT"
      ],
      "controlEstate": "phx-sam",
      "estate": "phx-sam_gater",
      "kingdom": "phx",
      "superPod": "None"
    },
    {
      "namespaces": [
        "communities"
      ],
      "access": [
        "team/communities"
      ],
      "controlEstate": "phx-sam",
      "estate": "phx-sam_moderation_einstein",
      "kingdom": "phx",
      "superPod": "None"
    },
    {
      "namespaces": [
        "csc-health"
      ],
      "access": [
        "team/CSC_Health"
      ],
      "controlEstate": "phx-sam",
      "estate": "phx-sam_report_collector",
      "kingdom": "phx",
      "superPod": "None"
    },
    {
      "namespaces": [
        "sf-store",
        "storage-foundation"
      ],
      "access": [
        "team/SF_Store",
        "team/Storage_Foundation"
      ],
      "controlEstate": "phx-sam",
      "estate": "phx-sam_sfstore",
      "kingdom": "phx",
      "superPod": "None"
    },
    {
      "namespaces": [
        "casp"
      ],
      "access": [
        "team/CASP"
      ],
      "controlEstate": "phx-sam",
      "estate": "phx-sam_warden",
      "kingdom": "phx",
      "superPod": "None"
    },
    {
      "namespaces": [
        "search-scale-safely"
      ],
      "access": [
        "team/Search_Scale_Safely"
      ],
      "controlEstate": "phx-sam",
      "estate": "phx-search_model_executor",
      "kingdom": "phx",
      "superPod": "None"
    },
    {
      "namespaces": [
        "cache-as-a-service-sp1"
      ],
      "access": [
        "team/Cache_As_A_service"
      ],
      "controlEstate": "phx-sam",
      "estate": "phx-sp1-sam_caas",
      "kingdom": "phx",
      "superPod": "sp1"
    },
    {
      "namespaces": [
        "cache-as-a-service-sp2"
      ],
      "access": [
        "team/Cache_As_A_service"
      ],
      "controlEstate": "phx-sam",
      "estate": "phx-sp2-sam_caas",
      "kingdom": "phx",
      "superPod": "sp2"
    },
    {
      "namespaces": [
        "cache-as-a-service-sp3"
      ],
      "access": [
        "team/Cache_As_A_service"
      ],
      "controlEstate": "phx-sam",
      "estate": "phx-sp3-sam_caas",
      "kingdom": "phx",
      "superPod": "sp3"
    },
    {
      "namespaces": [
        "cache-as-a-service-sp4"
      ],
      "access": [
        "team/Cache_As_A_service"
      ],
      "controlEstate": "phx-sam",
      "estate": "phx-sp4-sam_caas",
      "kingdom": "phx",
      "superPod": "sp4"
    },
    {
      "namespaces": [
        "*"
      ],
      "access": [
        "*"
      ],
      "controlEstate": "prd-sam",
      "estate": "prd-sam",
      "kingdom": "prd",
      "superPod": "None"
    },
    {
      "namespaces": [
        "legostore",
        "storage-foundation"
      ],
      "access": [
        "team/LegoStore",
        "team/Storage_Foundation"
      ],
      "controlEstate": "prd-sam",
      "estate": "prd-sam_ceph",
      "kingdom": "prd",
      "superPod": "None"
    },
    {
      "namespaces": [
        "legostore",
        "storage-foundation"
      ],
      "access": [
        "team/LegoStore",
        "team/Storage_Foundation"
      ],
      "controlEstate": "prd-sam_storage",
      "estate": "prd-sam_cephdev",
      "kingdom": "prd",
      "superPod": "None"
    },
    {
      "namespaces": [
        "chatbot"
      ],
      "access": [
        "team/chatbot"
      ],
      "controlEstate": "prd-sam",
      "estate": "prd-sam_chatbot_kingdom",
      "kingdom": "prd",
      "superPod": "None"
    },
    {
      "namespaces": [
        "cloudatlas"
      ],
      "access": [
        "team/CloudAtlas"
      ],
      "controlEstate": "prd-sam",
      "estate": "prd-sam_cloudatlas",
      "kingdom": "prd",
      "superPod": "None"
    },
    {
      "namespaces": [
        "cloudatlas"
      ],
      "access": [
        "team/CloudAtlas"
      ],
      "controlEstate": "prd-sam",
      "estate": "prd-sam_cloudatlas_dir",
      "kingdom": "prd",
      "superPod": "None"
    },
    {
      "namespaces": [
        "retail-mds",
        "retail-dfs",
        "retail-eventlistener"
      ],
      "access": [
        "team/Retail_MDS",
        "team/Retail_DFS",
        "team/Retail_EventListener"
      ],
      "controlEstate": "prd-sam",
      "estate": "prd-sam_crosscloudplatform",
      "kingdom": "prd",
      "superPod": "None"
    },
    {
      "namespaces": [
        "retail-rsui"
      ],
      "access": [
        "team/Retail_RSUI"
      ],
      "controlEstate": "prd-sam",
      "estate": "prd-sam_crosscloudsetup",
      "kingdom": "prd",
      "superPod": "None"
    },
    {
      "namespaces": [
        "retail-cre",
        "retail-credata"
      ],
      "access": [
        "team/Retail_CRE",
        "team/Retail_CREDATA"
      ],
      "controlEstate": "prd-sam",
      "estate": "prd-sam_customerresolutionengine",
      "kingdom": "prd",
      "superPod": "None"
    },
    {
      "namespaces": [
        "gater",
        "ccait",
        "service-mesh"
      ],
      "access": [
        "team/Gater",
        "team/CCAIT",
        "team/Service_Mesh"
      ],
      "controlEstate": "prd-sam",
      "estate": "prd-sam_gater",
      "kingdom": "prd",
      "superPod": "None"
    },
    {
      "namespaces": [
        "communities"
      ],
      "access": [
        "team/communities"
      ],
      "controlEstate": "prd-sam",
      "estate": "prd-sam_moderation_einstein",
      "kingdom": "prd",
      "superPod": "None"
    },
    {
      "namespaces": [
        "csc-health"
      ],
      "access": [
        "team/CSC_Health"
      ],
      "controlEstate": "prd-sam",
      "estate": "prd-sam_report_collector",
      "kingdom": "prd",
      "superPod": "None"
    },
    {
      "namespaces": [
        "sf-store",
        "storage-foundation"
      ],
      "access": [
        "team/SF_Store",
        "team/Storage_Foundation"
      ],
      "controlEstate": "prd-sam",
      "estate": "prd-sam_sfstore",
      "kingdom": "prd",
      "superPod": "None"
    },
    {
      "namespaces": [
        "sf-store",
        "storage-foundation"
      ],
      "access": [
        "team/SF_Store",
        "team/Storage_Foundation"
      ],
      "controlEstate": "prd-sam_storage",
      "estate": "prd-sam_sfstoredev",
      "kingdom": "prd",
      "superPod": "None"
    },
    {
      "namespaces": [
        "storage-foundation",
        "sf-store",
        "legostore"
      ],
      "access": [
        "team/Storage_Foundation",
        "team/SF_Store",
        "team/LegoStore"
      ],
      "controlEstate": "prd-sam_storage",
      "estate": "prd-sam_storage",
      "kingdom": "prd",
      "superPod": "None"
    },
    {
      "namespaces": [
        "casp"
      ],
      "access": [
        "team/CASP"
      ],
      "controlEstate": "prd-sam",
      "estate": "prd-sam_warden",
      "kingdom": "prd",
      "superPod": "None"
    },
    {
      "namespaces": [
        "*"
      ],
      "access": [
        "*"
      ],
      "controlEstate": "prd-samdev",
      "estate": "prd-samdev",
      "kingdom": "prd",
      "superPod": "None"
    },
    {
      "namespaces": [
        "*"
      ],
      "access": [
        "*"
      ],
      "controlEstate": "prd-samdev",
      "estate": "prd-samdevsandbox",
      "kingdom": "prd",
      "superPod": "None"
    },
    {
      "namespaces": [
        "*"
      ],
      "access": [
        "*"
      ],
      "controlEstate": "prd-samdev",
      "estate": "prd-samdevspare",
      "kingdom": "prd",
      "superPod": "None"
    },
    {
      "namespaces": [
        "*"
      ],
      "access": [
        "*"
      ],
      "controlEstate": "prd-sam",
      "estate": "prd-samsandbox",
      "kingdom": "prd",
      "superPod": "None"
    },
    {
      "namespaces": [
        "*"
      ],
      "access": [
        "*"
      ],
      "controlEstate": "prd-sam",
      "estate": "prd-samspare",
      "kingdom": "prd",
      "superPod": "None"
    },
    {
      "namespaces": [
        "*"
      ],
      "access": [
        "*"
      ],
      "controlEstate": "prd-samtest",
      "estate": "prd-samtest",
      "kingdom": "prd",
      "superPod": "None"
    },
    {
      "namespaces": [
        "*"
      ],
      "access": [
        "*"
      ],
      "controlEstate": "prd-samtest",
      "estate": "prd-samtestsandbox",
      "kingdom": "prd",
      "superPod": "None"
    },
    {
      "namespaces": [
        "*"
      ],
      "access": [
        "*"
      ],
      "controlEstate": "prd-samtest",
      "estate": "prd-samtestspare",
      "kingdom": "prd",
      "superPod": "None"
    },
    {
      "namespaces": [
        "*"
      ],
      "access": [
        "*"
      ],
      "controlEstate": "prd-sdc",
      "estate": "prd-sdc",
      "kingdom": "prd",
      "superPod": "None"
    },
    {
      "namespaces": [
        "search-scale-safely"
      ],
      "access": [
        "team/Search_Scale_Safely"
      ],
      "controlEstate": "prd-sam",
      "estate": "prd-search_model_executor",
      "kingdom": "prd",
      "superPod": "None"
    },
    {
      "namespaces": [
        "sayonaradb",
        "user-sraspudic"
      ],
      "access": [
        "team/Sayonaradb",
        "user/sraspudic"
      ],
      "controlEstate": "prd-sam",
      "estate": "prd-sp1-sdb_kube",
      "kingdom": "prd",
      "superPod": "None"
    },
    {
      "namespaces": [
        "cache-as-a-service-sp2"
      ],
      "access": [
        "team/Cache_As_A_service"
      ],
      "controlEstate": "prd-sam",
      "estate": "prd-sp2-sam_caas",
      "kingdom": "prd",
      "superPod": "sp2"
    },
    {
      "namespaces": [
        "chatbot-sp2"
      ],
      "access": [
        "team/chatbot"
      ],
      "controlEstate": "prd-sam",
      "estate": "prd-sp2-sam_chatbot",
      "kingdom": "prd",
      "superPod": "sp2"
    },
    {
      "namespaces": [
        "emailinfra-sp2"
      ],
      "access": [
        "team/EmailInfra"
      ],
      "controlEstate": "prd-sam",
      "estate": "prd-sp2-sam_eaas_sp",
      "kingdom": "prd",
      "superPod": "sp2"
    },
    {
      "namespaces": [
        "iot-sp2"
      ],
      "access": [
        "team/IoT"
      ],
      "controlEstate": "prd-sam",
      "estate": "prd-sp2-sam_iot_test",
      "kingdom": "prd",
      "superPod": "sp2"
    },
    {
      "namespaces": [
        "retail-cre-sp2"
      ],
      "access": [
        "team/Retail_CRE"
      ],
      "controlEstate": "prd-sam",
      "estate": "prd-sp2-sam_retail_cre",
      "kingdom": "prd",
      "superPod": "sp2"
    },
    {
      "namespaces": [
        "retail-credata-sp2"
      ],
      "access": [
        "team/Retail_CREDATA"
      ],
      "controlEstate": "prd-sam",
      "estate": "prd-sp2-sam_retail_credata",
      "kingdom": "prd",
      "superPod": "sp2"
    },
    {
      "namespaces": [
        "retail-dss-sp2"
      ],
      "access": [
        "team/Retail_DSS"
      ],
      "controlEstate": "prd-sam",
      "estate": "prd-sp2-sam_retail_dss",
      "kingdom": "prd",
      "superPod": "sp2"
    },
    {
      "namespaces": [
        "retail-eventlistener-sp2"
      ],
      "access": [
        "team/Retail_EventListener"
      ],
      "controlEstate": "prd-sam",
      "estate": "prd-sp2-sam_retail_eventlistener",
      "kingdom": "prd",
      "superPod": "sp2"
    },
    {
      "namespaces": [
        "retail-mds-sp2"
      ],
      "access": [
        "team/Retail_MDS"
      ],
      "controlEstate": "prd-sam",
      "estate": "prd-sp2-sam_retail_mds",
      "kingdom": "prd",
      "superPod": "sp2"
    },
    {
      "namespaces": [
        "retail-rsui-sp2"
      ],
      "access": [
        "team/Retail_RSUI"
      ],
      "controlEstate": "prd-sam",
      "estate": "prd-sp2-sam_retail_rsui",
      "kingdom": "prd",
      "superPod": "sp2"
    },
    {
      "namespaces": [
        "csc-sam"
      ],
      "access": [
        "team/CSC_Sam"
      ],
      "controlEstate": "syd-sam",
      "estate": "syd-sam",
      "kingdom": "syd",
      "superPod": "None"
    },
    {
      "namespaces": [
        "gater"
      ],
      "access": [
        "team/Gater"
      ],
      "controlEstate": "syd-sam",
      "estate": "syd-sam_gater",
      "kingdom": "syd",
      "superPod": "None"
    },
    {
      "namespaces": [
        "csc-sam"
      ],
      "access": [
        "team/CSC_Sam"
      ],
      "controlEstate": "ukb-sam",
      "estate": "ukb-sam",
      "kingdom": "ukb",
      "superPod": "None"
    },
    {
      "namespaces": [
        "legostore",
        "storage-foundation"
      ],
      "access": [
        "team/LegoStore",
        "team/Storage_Foundation"
      ],
      "controlEstate": "ukb-sam",
      "estate": "ukb-sam_ceph",
      "kingdom": "ukb",
      "superPod": "None"
    },
    {
      "namespaces": [
        "chatbot"
      ],
      "access": [
        "team/chatbot"
      ],
      "controlEstate": "ukb-sam",
      "estate": "ukb-sam_chatbot_kingdom",
      "kingdom": "ukb",
      "superPod": "None"
    },
    {
      "namespaces": [
        "cloudatlas"
      ],
      "access": [
        "team/CloudAtlas"
      ],
      "controlEstate": "ukb-sam",
      "estate": "ukb-sam_cloudatlas",
      "kingdom": "ukb",
      "superPod": "None"
    },
    {
      "namespaces": [
        "cloudatlas"
      ],
      "access": [
        "team/CloudAtlas"
      ],
      "controlEstate": "ukb-sam",
      "estate": "ukb-sam_cloudatlas_dir",
      "kingdom": "ukb",
      "superPod": "None"
    },
    {
      "namespaces": [
        "gater"
      ],
      "access": [
        "team/Gater"
      ],
      "controlEstate": "ukb-sam",
      "estate": "ukb-sam_gater",
      "kingdom": "ukb",
      "superPod": "None"
    },
    {
      "namespaces": [
        "communities"
      ],
      "access": [
        "team/communities"
      ],
      "controlEstate": "ukb-sam",
      "estate": "ukb-sam_moderation_einstein",
      "kingdom": "ukb",
      "superPod": "None"
    },
    {
      "namespaces": [
        "csc-health"
      ],
      "access": [
        "team/CSC_Health"
      ],
      "controlEstate": "ukb-sam",
      "estate": "ukb-sam_report_collector",
      "kingdom": "ukb",
      "superPod": "None"
    },
    {
      "namespaces": [
        "sf-store",
        "storage-foundation"
      ],
      "access": [
        "team/SF_Store",
        "team/Storage_Foundation"
      ],
      "controlEstate": "ukb-sam",
      "estate": "ukb-sam_sfstore",
      "kingdom": "ukb",
      "superPod": "None"
    },
    {
      "namespaces": [
        "casp"
      ],
      "access": [
        "team/CASP"
      ],
      "controlEstate": "ukb-sam",
      "estate": "ukb-sam_warden",
      "kingdom": "ukb",
      "superPod": "None"
    },
    {
      "namespaces": [
        "cache-as-a-service-sp1"
      ],
      "access": [
        "team/Cache_As_A_service"
      ],
      "controlEstate": "ukb-sam",
      "estate": "ukb-sp1-sam_caas",
      "kingdom": "ukb",
      "superPod": "sp1"
    },
    {
      "namespaces": [
        "csc-sam"
      ],
      "access": [
        "team/CSC_Sam"
      ],
      "controlEstate": "wax-sam",
      "estate": "wax-sam",
      "kingdom": "wax",
      "superPod": "None"
    },
    {
      "namespaces": [
        "gater"
      ],
      "access": [
        "team/Gater"
      ],
      "controlEstate": "wax-sam",
      "estate": "wax-sam_gater",
      "kingdom": "wax",
      "superPod": "None"
    },
    {
      "namespaces": [
        "csc-sam"
      ],
      "access": [
        "team/CSC_Sam"
      ],
      "controlEstate": "yhu-sam",
      "estate": "yhu-sam",
      "kingdom": "yhu",
      "superPod": "None"
    },
    {
      "namespaces": [
        "gater"
      ],
      "access": [
        "team/Gater"
      ],
      "controlEstate": "yhu-sam",
      "estate": "yhu-sam_gater",
      "kingdom": "yhu",
      "superPod": "None"
    },
    {
      "namespaces": [
        "csc-sam"
      ],
      "access": [
        "team/CSC_Sam"
      ],
      "controlEstate": "yul-sam",
      "estate": "yul-sam",
      "kingdom": "yul",
      "superPod": "None"
    },
    {
      "namespaces": [
        "gater"
      ],
      "access": [
        "team/Gater"
      ],
      "controlEstate": "yul-sam",
      "estate": "yul-sam_gater",
      "kingdom": "yul",
      "superPod": "None"
    }
  ]
}