#!/bin/bash -xe

set -ex

# Check whether build.sh output matches applied changes
pushd ./sam-internal/k8s-in
./build.sh > /dev/null
if [[ `git status --porcelain` ]]; then
  echo "build.sh output does not match applied changes"
  exit 1
fi
pushd ../..

./validate.sh evaluatePR
