#!/bin/bash -xe

# Standard setup and printing of debug information.  Keep in sync with other scripts.
set -exv
cd $(dirname ${0})
cd ..
echo "Current directory"
pwd
echo "Git information"
git version
git log -n 1
# End of standard setup

while getopts ":o:" opt; do
  case $opt in
    o)
      OUTPUT_DIR=$OPTARG
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

# Disable estates check for now until we work out the access token stuff
/opt/sam/sam-manifest-builder -logtostderr -output ${OUTPUT_DIR} -estatescheck=false -tnrppipelinelabel ${TNRP_PIPELINE_LABEL} -root . -imagefileoutdir . -internalpassthrough k8s-out,sdn,authorizer
cp ./image-promotion.yaml ${OUTPUT_DIR}

# Temporary for now
env > ${OUTPUT_DIR}/debug_env.txt
git log -n 1 > ${OUTPUT_DIR}/debug_gitlog.txt
