#!/bin/bash -xe

# Standard setup and printing of debug information.  Keep in sync with other scripts.
set -exv
cd $(dirname ${0})
cd ..
echo "Current directory"
pwd
echo "Git information"
git version
git log -n 1
# End of standard setup

if [ -z "$FIREFLY" ]; then
   SAMBINDIR=/opt/sam
else
   echo "*** EXECUTING IN $FIREFLY ENVIRONMENT"
   SAMBINDIR=/sam
   yum install -y slb-manifest-builder-20190307_231911.4f58886.clean.fef44d58cff4-1.x86_64
fi


while getopts ":o:" opt; do
  case $opt in
    o)
      OUTPUT_DIR=$OPTARG
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

#Generate git history file
$SAMBINDIR/manifestctl manifest-git-info --inputDir . -outputPath ${OUTPUT_DIR}/git-info.yaml -gitHistoryMode lib -alsologtostderr
 # Disable estates check for now until we work out the access token stuff
$SAMBINDIR/sam-manifest-builder -logtostderr -output ${OUTPUT_DIR} -estatescheck=false -tnrppipelinelabel ${TNRP_PIPELINE_LABEL} -root . -validationExceptionsFile=./sam-internal/validation-whitelist.yaml --swaggerspecdir=$SAMBINDIR/swagger-spec -imagefileoutdir . -internalpassthrough k8s-out,sdn,authorizer -gitHistoryInfoFile ${OUTPUT_DIR}/git-info.yaml -skip-sam-internals -alsologtostderr

$SAMBINDIR/manifestctl build-repo -inputManifestDir . -outputDir ${OUTPUT_DIR} -alsologtostderr

$SAMBINDIR/manifestctl compare-manifests -oldManifestDir=${OUTPUT_DIR}/goal-state -newManifestDir=${OUTPUT_DIR}/goal

# Copy over vips.yaml files for SLB
/opt/slb/slb-manifest-builder -root . -output ${OUTPUT_DIR} -v=2


cp ./image-promotion.yaml ${OUTPUT_DIR}

# Temporary for now
env > ${OUTPUT_DIR}/debug_env.txt
git log -n 1 > ${OUTPUT_DIR}/debug_gitlog.txt
