## Autogenerated file.


local nsbase = import "namespaces/mesh-namespaces.jsonnet";
local configs = import "config.jsonnet";
if (nsbase.shouldDeployToKingdom("universal-search", configs.kingdom)) then
        nsbase.newMeshNamespace("universal-search")
else "SKIP"
