## Autogenerated file.


local nsbase = import "namespaces/mesh-namespaces.jsonnet";
local configs = import "config.jsonnet";
if (nsbase.shouldDeployToKingdom("funnel", configs.kingdom)) then
        nsbase.newMeshNamespace("funnel")
else "SKIP"
