## Autogenerated file.


local nsbase = import "namespaces/mesh-namespaces.jsonnet";
local configs = import "config.jsonnet";
if (nsbase.shouldDeployToKingdom("gater", configs.kingdom)) then
        nsbase.newMeshNamespace("gater")
else "SKIP"
