## Autogenerated file.


local nsbase = import "namespaces/mesh-namespaces.jsonnet";
local configs = import "config.jsonnet";
if (nsbase.shouldDeployToKingdom("app", configs.kingdom)) then
        nsbase.newMeshNamespace("app")
else "SKIP"
