## Autogenerated file.


local nsbase = import "namespaces/mesh-namespaces.jsonnet";
local configs = import "config.jsonnet";
if (nsbase.shouldDeployToKingdom("search-scale-safely", configs.kingdom)) then
        nsbase.newMeshNamespace("search-scale-safely")
else "SKIP"
