## Autogenerated file.


local nsbase = import "namespaces/mesh-namespaces.jsonnet";
local configs = import "config.jsonnet";
if (nsbase.shouldDeployToKingdom("core-on-sam-sp2", configs.kingdom)) then
        nsbase.newMeshNamespace("core-on-sam-sp2")
else "SKIP"
