## Autogenerated file.


local nsbase = import "namespaces/mesh-namespaces.jsonnet";
local configs = import "config.jsonnet";
if (nsbase.shouldDeployToKingdom("retail-dss", configs.kingdom)) then
        nsbase.newMeshNamespace("retail-dss")
else "SKIP"
