## Autogenerated file.


local nsbase = import "namespaces/mesh-namespaces.jsonnet";
local configs = import "config.jsonnet";
if (nsbase.shouldDeployToKingdom("retail-dfs", configs.kingdom)) then
        nsbase.newMeshNamespace("retail-dfs")
else "SKIP"
