## Autogenerated file.


local nsbase = import "namespaces/mesh-namespaces.jsonnet";
local configs = import "config.jsonnet";
if (nsbase.shouldDeployToKingdom("retail-eventlistener", configs.kingdom)) then
        nsbase.newMeshNamespace("retail-eventlistener")
else "SKIP"
