## Autogenerated file.


local nsbase = import "namespaces/mesh-namespaces.jsonnet";
local configs = import "config.jsonnet";
if (nsbase.shouldDeployToKingdom("casam", configs.kingdom)) then
        nsbase.newMeshNamespace("casam")
else "SKIP"
