## Autogenerated file.


local nsbase = import "namespaces/mesh-namespaces.jsonnet";
local configs = import "config.jsonnet";
if (nsbase.shouldDeployToKingdom("retail-setup", configs.kingdom)) then
        nsbase.newMeshNamespace("retail-setup")
else "SKIP"
