## Autogenerated file.


local nsbase = import "namespaces/mesh-namespaces.jsonnet";
local configs = import "config.jsonnet";
if (nsbase.shouldDeployToKingdom("retail-rsui", configs.kingdom)) then
        nsbase.newMeshNamespace("retail-rsui")
else "SKIP"
