## Autogenerated file.


local nsbase = import "namespaces/mesh-namespaces.jsonnet";
local configs = import "config.jsonnet";
if (nsbase.shouldDeployToKingdom("service-mesh", configs.kingdom)) then
        nsbase.newMeshNamespace("service-mesh")
else "SKIP"
