## Autogenerated file.


local nsbase = import "namespaces/mesh-namespaces.jsonnet";
local configs = import "config.jsonnet";
if (nsbase.shouldDeployToKingdom("cloudatlas", configs.kingdom)) then
        nsbase.newMeshNamespace("cloudatlas")
else "SKIP"
